# Generated by Django 6.1 on 2026-08-20 12:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la commune')),
                ('code_commune', models.CharField(max_length=20, unique=True, verbose_name='Code commune')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Limite de la commune')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name="Type d'établissement")),
            ],
            options={
                'verbose_name': "Type d'établissement",
                'verbose_name_plural': "Types d'établissements",
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du quartier')),
                ('code_quartier', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code quartier')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Limite du quartier')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='sante.commune', verbose_name='Commune')),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('effectif', models.BigIntegerField(verbose_name='Population')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='sante.commune', verbose_name='Commune')),
                ('quartier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='sante.quartier', verbose_name='Quartier')),
            ],
            options={
                'verbose_name': 'Population',
                'verbose_name_plural': 'Populations',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='EtablissementSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'établissement")),
                ('milieu', models.CharField(blank=True, choices=[('URBAIN', 'Urbain'), ('PERI', 'Péri-urbain'), ('RURAL', 'Rural')], max_length=10, null=True, verbose_name='Milieu')),
                ('statut', models.CharField(blank=True, choices=[('PUBLIC', 'Public'), ('PRIVE', 'Privé'), ('COMM', 'Communautaire'), ('MIL', 'Militaire'), ('AUTRE', 'Autre')], max_length=10, null=True, verbose_name='Statut')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Localisation')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etablissements', to='sante.commune', verbose_name='Commune')),
                ('quartier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements', to='sante.quartier', verbose_name='Quartier')),
                ('type_etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etablissements', to='sante.typeetablissement', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Établissement de santé',
                'verbose_name_plural': 'Établissements de santé',
                'ordering': ['nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='quartier',
            constraint=models.UniqueConstraint(fields=('nom', 'commune'), name='unique_quartier_commune'),
        ),
        migrations.AddIndex(
            model_name='etablissementsante',
            index=models.Index(fields=['type_etablissement'], name='sante_etabl_type_et_88abd7_idx'),
        ),
        migrations.AddIndex(
            model_name='etablissementsante',
            index=models.Index(fields=['commune'], name='sante_etabl_commune_138970_idx'),
        ),
        migrations.AddIndex(
            model_name='etablissementsante',
            index=models.Index(fields=['quartier'], name='sante_etabl_quartie_6f3862_idx'),
        ),
        migrations.AddIndex(
            model_name='etablissementsante',
            index=models.Index(fields=['statut'], name='sante_etabl_statut_d7f1b3_idx'),
        ),
    ]
