# Generated by Django 6.1 on 2026-08-20 13:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='arrondissement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Arrondissement'),
        ),
        migrations.AddField(
            model_name='commune',
            name='code_commune_arrondissement',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code CAV'),
        ),
        migrations.AddField(
            model_name='commune',
            name='commune_arrondissement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Commune d'arrondissement (CAV)"),
        ),
        migrations.AddField(
            model_name='commune',
            name='numero_commune',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro de la commune'),
        ),
        migrations.AddField(
            model_name='etablissementsante',
            name='objectid',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID objet SIG (source)'),
        ),
        migrations.AddField(
            model_name='quartier',
            name='numero_quartier',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro du quartier'),
        ),
        migrations.AddField(
            model_name='quartier',
            name='statut_occupation',
            field=models.CharField(blank=True, choices=[('HABITEE', 'Habitée'), ('NON_HABITEE', 'Non habitée')], max_length=15, null=True, verbose_name="Statut d'occupation"),
        ),
        migrations.AddField(
            model_name='quartier',
            name='type_quartier',
            field=models.CharField(blank=True, choices=[('QUARTIER', 'Quartier'), ('VILLAGE', 'Village'), ('HAMEAU', 'Hameau')], max_length=15, null=True, verbose_name='Type (quartier/village/hameau)'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Limite de la commune'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom de la commune'),
        ),
        migrations.AddIndex(
            model_name='etablissementsante',
            index=models.Index(fields=['objectid'], name='sante_etabl_objecti_272c29_idx'),
        ),
    ]
